[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jila"
version = "0.1.0"
description = "CLI for managing Jila projects"
readme = "README.md"
authors = [{ name = "Shortice" }]
dependencies = [
    "click",
]
requires-python = ">=3.8"

[project.scripts]
jila = "jila.main:cli"

[tool.setuptools]
package-dir = {"" = "jila-manager"}

[tool.setuptools.packages.find]
where = ["jila-manager"]
include = ["jila*"]
