---@meta c_flags
---
---Flags and enums.
--- Col's

--- @type number
ImGuiCol_Text = ...

--- @type number
ImGuiCol_TextDisabled = ...

--- @type number
ImGuiCol_WindowBg = ...

--- @type number
ImGuiCol_ChildBg = ...

--- @type number
ImGuiCol_PopupBg = ...

--- @type number
ImGuiCol_Border = ...

--- @type number
ImGuiCol_BorderShadow = ...

--- @type number
ImGuiCol_FrameBg = ...

--- @type number
ImGuiCol_FrameBgHovered = ...

--- @type number
ImGuiCol_FrameBgActive = ...

--- @type number
ImGuiCol_TitleBg = ...

--- @type number
ImGuiCol_TitleBgActive = ...

--- @type number
ImGuiCol_TitleBgCollapsed = ...

--- @type number
ImGuiCol_MenuBarBg = ...

--- @type number
ImGuiCol_ScrollbarBg = ...

--- @type number
ImGuiCol_ScrollbarGrab = ...

--- @type number
ImGuiCol_ScrollbarGrabHovered = ...

--- @type number
ImGuiCol_ScrollbarGrabActive = ...

--- @type number
ImGuiCol_CheckMark = ...

--- @type number
ImGuiCol_SliderGrab = ...

--- @type number
ImGuiCol_SliderGrabActive = ...

--- @type number
ImGuiCol_Button = ...

--- @type number
ImGuiCol_ButtonHovered = ...

--- @type number
ImGuiCol_ButtonActive = ...

--- @type number
ImGuiCol_Header = ...

--- @type number
ImGuiCol_HeaderHovered = ...

--- @type number
ImGuiCol_HeaderActive = ...

--- @type number
ImGuiCol_Separator = ...

--- @type number
ImGuiCol_SeparatorHovered = ...

--- @type number
ImGuiCol_SeparatorActive = ...

--- @type number
ImGuiCol_ResizeGrip = ...

--- @type number
ImGuiCol_ResizeGripHovered = ...

--- @type number
ImGuiCol_ResizeGripActive = ...

--- @type number
ImGuiCol_InputTextCursor = ...

--- @type number
ImGuiCol_TabHovered = ...

--- @type number
ImGuiCol_Tab = ...

--- @type number
ImGuiCol_TabSelected = ...

--- @type number
ImGuiCol_TabSelectedOverline = ...

--- @type number
ImGuiCol_TabDimmed = ...

--- @type number
ImGuiCol_TabDimmedSelected = ...

--- @type number
ImGuiCol_TabDimmedSelectedOverline = ...

--- @type number
ImGuiCol_PlotLines = ...

--- @type number
ImGuiCol_PlotLinesHovered = ...

--- @type number
ImGuiCol_PlotHistogram = ...

--- @type number
ImGuiCol_PlotHistogramHovered = ...

--- @type number
ImGuiCol_TableHeaderBg = ...

--- @type number
ImGuiCol_TableBorderStrong = ...

--- @type number
ImGuiCol_TableBorderLight = ...

--- @type number
ImGuiCol_TableRowBg = ...

--- @type number
ImGuiCol_TableRowBgAlt = ...

--- @type number
ImGuiCol_TextLink = ...

--- @type number
ImGuiCol_TextSelectedBg = ...

--- @type number
ImGuiCol_TreeLines = ...

--- @type number
ImGuiCol_DragDropTarget = ...

--- @type number
ImGuiCol_NavCursor = ...

--- @type number
ImGuiCol_NavWindowingHighlight = ...

--- @type number
ImGuiCol_NavWindowingDimBg = ...

--- @type number
ImGuiCol_ModalWindowDimBg = ...

-----------------------------------
-------------- Флаги --------------
-----------------------------------

--- @type number
ImGuiTreeNodeFlags_None = ...

--- @type number
ImGuiTreeNodeFlags_Selected = ...

--- @type number
ImGuiTreeNodeFlags_Framed = ...

--- @type number
ImGuiTreeNodeFlags_AllowOverlap = ...

--- @type number
ImGuiTreeNodeFlags_NoTreePushOnOpen = ...

--- @type number
ImGuiTreeNodeFlags_NoOpenOnArrow = ...

--- @type number
ImGuiTreeNodeFlags_NoOpenOnDoubleClick = ...

--- @type number
ImGuiTreeNodeFlags_Leaf = ...

--- @type number
ImGuiTreeNodeFlags_Bullet = ...

--- @type number
ImGuiSliderFlags_None = ...

--- @type number
ImGuiSliderFlags_Logarithmic = ...

--- @type number
ImGuiSliderFlags_NoRoundToFormat = ...

--- @type number
ImGuiSliderFlags_NoInput = ...

--- @type number
ImGuiSliderFlags_ClampOnInput = ...

--- @type number
ImGuiColorEditFlags_None = ...

--- @type number
ImGuiColorEditFlags_NoAlpha = ...

--- @type number
ImGuiColorEditFlags_NoPicker = ...

--- @type number
ImGuiColorEditFlags_NoOptions = ...

--- @type number
ImGuiColorEditFlags_NoSmallPreview = ...

--- @type number
ImGuiColorEditFlags_NoInputs = ...

--- @type number
ImGuiColorEditFlags_NoTooltip = ...

--- @type number
ImGuiColorEditFlags_NoLabel = ...

--- @type number
ImGuiColorEditFlags_NoDragDrop = ...

--- @type number
ImGuiColorEditFlags_NoBorder = ...

--- @type number
ImGuiStyleVar_Alpha = ...

--- @type number
ImGuiStyleVar_WindowPadding = ...

--- @type number
ImGuiStyleVar_WindowRounding = ...

--- @type number
ImGuiStyleVar_WindowBorderSize = ...

--- @type number
ImGuiStyleVar_WindowMinSize = ...

--- @type number
ImGuiStyleVar_WindowTitleAlign = ...

--- @type number
ImGuiMouseButton_Left = ...

--- @type number
ImGuiMouseButton_Right = ...

--- @type number
ImGuiMouseButton_Middle = ...

--- @type number
ImGuiKey_Tab = ...

--- @type number
ImGuiKey_LeftArrow = ...

--- @type number
ImGuiKey_RightArrow = ...

--- @type number
ImGuiKey_UpArrow = ...

--- @type number
ImGuiKey_DownArrow = ...

--- @type number
ImGuiKey_PageUp = ...

--- @type number
ImGuiKey_PageDown = ...

--- @type number
ImGuiKey_Home = ...

--- @type number
ImGuiKey_End = ...

--- @type number
ImGuiKey_Insert = ...

--- @type number
ImGuiKey_Delete = ...

--- @type number
ImGuiKey_Backspace = ...

--- @type number
ImGuiKey_Space = ...

--- @type number
ImGuiKey_Enter = ...

--- @type number
ImGuiKey_Escape = ...

--- @type number
ImGuiKey_KeyPadEnter = ...

--- @type number
ImGuiKey_A = ...

--- @type number
ImGuiKey_C = ...

--- @type number
ImGuiKey_V = ...

--- @type number
ImGuiKey_X = ...

--- @type number
ImGuiKey_Y = ...

--- @type number
ImGuiKey_Z = ...

-----------------------------------
--------------- Window -------------
-----------------------------------

--- @type number
ImGuiWindowFlags_None = ...

--- @type number
ImGuiWindowFlags_NoTitleBar = ...

--- @type number
ImGuiWindowFlags_NoResize = ...

--- @type number
ImGuiWindowFlags_NoMove = ...

--- @type number
ImGuiWindowFlags_NoScrollbar = ...

--- @type number
ImGuiWindowFlags_NoScrollWithMouse = ...

--- @type number
ImGuiWindowFlags_NoCollapse = ...

--- @type number
ImGuiWindowFlags_AlwaysAutoResize = ...

--- @type number
ImGuiWindowFlags_NoBackground = ...

--- @type number
ImGuiWindowFlags_NoSavedSettings = ...

--- @type number
ImGuiWindowFlags_NoMouseInputs = ...

--- @type number
ImGuiWindowFlags_MenuBar = ...

--- @type number
ImGuiWindowFlags_HorizontalScrollbar = ...

--- @type number
ImGuiWindowFlags_NoFocusOnAppearing = ...

--- @type number
ImGuiWindowFlags_NoBringToFrontOnFocus = ...

--- @type number
ImGuiWindowFlags_AlwaysHorizontalScrollbar = ...

--- @type number
ImGuiWindowFlags_AlwaysVerticalScrollbar = ...

--- @type number
ImGuiWindowFlags_AlwaysUseWindowPadding = ...

--- @type number
ImGuiWindowFlags_NoNavInputs = ...

--- @type number
ImGuiWindowFlags_NoNavFocus = ...

--- @type number
ImGuiWindowFlags_NoNav = ...

--- @type number
ImGuiWindowFlags_NoDecoration = ...

--- @type number
ImGuiWindowFlags_NoInputs = ...

--- @type number
ImGuiWindowFlags_NavFlattened = ...

--- @type number
ImGuiWindowFlags_UnsavedDocument = ...

------------------------------------
--------------- Child ---------------
------------------------------------

--- @type number
ImGuiChildFlags_None = ...

--- @type number
ImGuiChildFlags_Borders = ...

--- @type number
ImGuiChildFlags_AlwaysUseWindowPadding = ...

--- @type number
ImGuiChildFlags_ResizeX = ...

--- @type number
ImGuiChildFlags_ResizeY = ...

--- @type number
ImGuiChildFlags_AutoResizeX = ...

--- @type number
ImGuiChildFlags_AutoResizeY = ...

--- @type number
ImGuiChildFlags_FrameStyle = ...
